import React, { useState } from 'react';
import { StartupIdea } from '../types';
import { 
  Rocket, TrendingUp, DollarSign, Target, RefreshCw, Download, Share2, 
  ExternalLink, Copy, CheckCircle, Eye, Zap as ZapIcon, Users as UsersIcon, 
  DollarSign as DollarIcon, Target as TargetIcon, Star, Crown, Award, ChevronRight,
  Loader2, Layout, X, Settings, Heart, Database, Image, Type, MousePointer, 
  Menu, BarChart3 as BarChartIcon, Activity, Navigation, Square, Circle, Shield, 
  HelpCircle, Info, User, Palette, Smartphone, Globe, Sparkles, FileText
} from 'lucide-react';
import { showToast } from '../utils/toast';
import { regenerateSection } from '../services/api';

interface StartupOutputProps {
  startup: StartupIdea;
  onRegenerate?: () => void;
  onGenerateBusinessModel?: () => void;
  onGenerateMockup?: () => void;
}

const StartupOutput: React.FC<StartupOutputProps> = ({
  startup,
  onRegenerate,
  onGenerateBusinessModel,
  onGenerateMockup,
}) => {
  const [activeSection, setActiveSection] = useState<'overview' | 'problem' | 'solution' | 'market' | 'business-model'>('overview');
  const [regeneratingSection, setRegeneratingSection] = useState<string | null>(null);
  const [isDownloading, setIsDownloading] = useState(false);
  const [isSharing, setIsSharing] = useState(false);
  const [showCanvas, setShowCanvas] = useState(false);
  const [showMockup, setShowMockup] = useState(false);
  const [canvasData, setCanvasData] = useState<any>(null);
  const [mockupData, setMockupData] = useState<any>(null);
  const [isGeneratingCanvas, setIsGeneratingCanvas] = useState(false);
  const [isGeneratingMockup, setIsGeneratingMockup] = useState(false);
  const [currentStartup, setCurrentStartup] = useState<StartupIdea>(startup);

  const sections = [
    { 
      id: 'overview', 
      label: 'Overview', 
      icon: Rocket, 
      color: 'from-primary to-secondary',
      gradient: 'from-purple-500 to-teal-500',
      description: 'Complete business overview'
    },
    { 
      id: 'problem', 
      label: 'Problem', 
      icon: Target, 
      color: 'from-red-500 to-red-600',
      gradient: 'from-red-400 to-red-600',
      description: 'The challenge we solve'
    },
    { 
      id: 'solution', 
      label: 'Solution', 
      icon: ZapIcon, 
      color: 'from-green-500 to-green-600',
      gradient: 'from-green-400 to-green-600',
      description: 'How we address it'
    },
    { 
      id: 'market', 
      label: 'Market', 
      icon: UsersIcon, 
      color: 'from-blue-500 to-blue-600',
      gradient: 'from-blue-400 to-blue-600',
      description: 'Target audience'
    },
    { 
      id: 'business', 
      label: 'Business Model', 
      icon: DollarIcon, 
      color: 'from-purple-500 to-purple-600',
      gradient: 'from-purple-400 to-purple-600',
      description: 'Revenue & strategy'
    },
  ];

  const handleRegenerateSection = async (sectionId: string) => {
    setRegeneratingSection(sectionId);
    showToast(`Regenerating ${sectionId} section...`, 'info');

    try {
      const data = await regenerateSection(currentStartup, sectionId);
      
      // Update the specific section
      setCurrentStartup(prev => ({
        ...prev,
        ...data
      }));

      showToast(`${sectionId} section regenerated successfully!`, 'success');
    } catch (error) {
      console.error('Error regenerating section:', error);
      
      // Fallback: show a message that this feature requires the backend
      showToast(`Regeneration requires backend connection. Please ensure the server is running.`, 'warning');
    } finally {
      setRegeneratingSection(null);
    }
  };

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      const content = `
${currentStartup.name}
"${currentStartup.tagline}"

OVERVIEW
${currentStartup.description}

COMPETITIVE ADVANTAGE
${currentStartup.competitiveAdvantage}

MONETIZATION
${currentStartup.monetization}

PROBLEM
${currentStartup.problem}

SOLUTION
${currentStartup.solution}

TARGET MARKET
${currentStartup.targetMarket}

BUSINESS MODEL
${currentStartup.businessModel}

TECH STACK
${currentStartup.techStack.join(', ')}

Generated by Dream Startup Generator
© 2024 Dream Startup Generator
      `;

      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${currentStartup.name.replace(/\s+/g, '_')}_Business_Plan.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      showToast('Business plan downloaded successfully!', 'success');
    } catch (error) {
      showToast('Error downloading business plan.', 'error');
    } finally {
      setIsDownloading(false);
    }
  };

  const handleShare = async () => {
    setIsSharing(true);
    try {
      const shareData = {
        title: currentStartup.name,
        text: `${currentStartup.name}: ${currentStartup.tagline}`,
        url: window.location.href,
      };

      if (navigator.share) {
        await navigator.share(shareData);
        showToast('Startup idea shared successfully!', 'success');
      } else {
        const shareText = `${currentStartup.name}\n"${currentStartup.tagline}"\n\n${currentStartup.description}\n\nGenerated by Dream Startup Generator`;
        await navigator.clipboard.writeText(shareText);
        showToast('Startup idea copied to clipboard!', 'success');
      }
    } catch (error) {
      showToast('Error sharing startup idea.', 'error');
    } finally {
      setIsSharing(false);
    }
  };

  const handleGenerateCanvas = () => {
    setIsGeneratingCanvas(true);
    showToast('Generating Business Model Canvas...', 'info');
    
    setTimeout(() => {
      const canvasData = {
        keyPartners: ['Technology providers', 'Marketing agencies', 'Strategic alliances'],
        keyActivities: ['Product development', 'Customer acquisition', 'Market research'],
        valuePropositions: currentStartup.tagline,
        customerRelationships: ['Personalized support', 'Community building', 'Continuous engagement'],
        customerSegments: currentStartup.targetMarket,
        keyResources: ['Development team', 'Technology infrastructure', 'Intellectual property'],
        channels: ['Online platforms', 'Partnerships', 'Direct sales'],
        costStructure: ['Development costs', 'Marketing expenses', 'Operational overhead'],
        revenueStreams: currentStartup.monetization
      };
      
      setCanvasData(canvasData);
      setShowCanvas(true);
      setIsGeneratingCanvas(false);
      showToast('Business Model Canvas generated!', 'success');
    }, 2000);
  };

  const handleGenerateMockup = () => {
    setIsGeneratingMockup(true);
    showToast('Generating App Mockup...', 'info');
    
    setTimeout(() => {
      const mockupData = {
        screens: [
          {
            name: 'Welcome Screen',
            elements: [
              { type: 'logo', content: currentStartup.name },
              { type: 'tagline', content: currentStartup.tagline },
              { type: 'cta', content: 'Get Started' },
              { type: 'background', content: 'Purple to teal gradient' }
            ]
          },
          {
            name: 'Main Dashboard',
            elements: [
              { type: 'profile', content: 'User profile section' },
              { type: 'menu', content: 'Quick actions menu' },
              { type: 'progress', content: 'Progress indicators' },
              { type: 'feed', content: 'Recent activity feed' }
            ]
          },
          {
            name: 'Core Feature',
            elements: [
              { type: 'interface', content: 'Main functionality interface' },
              { type: 'navigation', content: 'Navigation tabs' },
              { type: 'buttons', content: 'Action buttons' },
              { type: 'status', content: 'Status indicators' }
            ]
          },
          {
            name: 'Settings',
            elements: [
              { type: 'preferences', content: 'User preferences' },
              { type: 'account', content: 'Account management' },
              { type: 'help', content: 'Help & support' },
              { type: 'about', content: 'About section' }
            ]
          }
        ],
        designSystem: {
          primaryColors: ['Purple (#8b5cf6)', 'Teal (#14b8a6)'],
          typography: 'Inter font family',
          icons: 'Lucide React icon set',
          spacing: 'Consistent 8px grid system'
        }
      };
      
      setMockupData(mockupData);
      setShowMockup(true);
      setIsGeneratingMockup(false);
      showToast('App mockup generated!', 'success');
    }, 2000);
  };

  const renderSection = () => {
    switch (activeSection) {
      case 'overview':
        return (
          <div className="startup-overview animate-fade-in">
            <div className="startup-hero">
              <div className="startup-logo-container">
                <div className="startup-logo">
                  <Rocket size={48} className="text-white" />
                  <div className="startup-logo-glow"></div>
                </div>
              </div>
              <div className="startup-title-section">
                <h1 className="startup-name animate-slide-up">
                  {currentStartup.name}
                </h1>
                <p className="startup-tagline animate-slide-up" style={{animationDelay: '0.2s'}}>
                  "{currentStartup.tagline}"
                </p>
                <div className="startup-badges animate-slide-up" style={{animationDelay: '0.4s'}}>
                  <span className="startup-badge">
                    <Star size={16} />
                    Innovative
                  </span>
                  <span className="startup-badge">
                    <TrendingUp size={16} />
                    Scalable
                  </span>
                  <span className="startup-badge">
                    <Award size={16} />
                    Award-Winning
                  </span>
                </div>
              </div>
            </div>
            
            <div className="startup-description animate-slide-up" style={{animationDelay: '0.6s'}}>
              <div className="description-bullets">
                {currentStartup.description.split('. ').slice(0, 5).map((point, index) => (
                  <div key={index} className="description-bullet" style={{animationDelay: `${0.6 + index * 0.1}s`}}>
                    <div className="bullet-icon">
                      <Sparkles size={16} />
                    </div>
                    <span className="bullet-text">{point.trim()}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="startup-features animate-slide-up" style={{animationDelay: '0.8s'}}>
              <div className="feature-card hover-lift">
                <div className="feature-icon">
                  <TrendingUp size={32} className="text-white" />
                </div>
                <div className="feature-content">
                  <h4 className="feature-title">Competitive Advantage</h4>
                  <div className="feature-bullets">
                    {currentStartup.competitiveAdvantage.split('. ').slice(0, 5).map((point, index) => (
                      <div key={index} className="feature-bullet">
                        <div className="bullet-dot"></div>
                        <span className="bullet-text">{point.trim()}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
              <div className="feature-card hover-lift">
                <div className="feature-icon">
                  <DollarSign size={32} className="text-white" />
                </div>
                <div className="feature-content">
                  <h4 className="feature-title">Monetization</h4>
                  <div className="feature-bullets">
                    {currentStartup.monetization.split('. ').slice(0, 5).map((point, index) => (
                      <div key={index} className="feature-bullet">
                        <div className="bullet-dot"></div>
                        <span className="bullet-text">{point.trim()}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        );
      case 'problem':
        return (
          <div className="section-content animate-fade-in">
            <div className="section-header">
              <div className="section-icon">
                <Target size={32} className="text-white" />
              </div>
              <div className="section-title-group">
                <h3 className="section-title">The Problem</h3>
                <p className="section-subtitle">Understanding the challenge we're solving</p>
              </div>
              <button
                onClick={() => handleRegenerateSection('problem')}
                disabled={regeneratingSection === 'problem'}
                className="section-regenerate-btn"
                title="Regenerate this section"
              >
                {regeneratingSection === 'problem' ? (
                  <Loader2 size={18} className="animate-spin" />
                ) : (
                  <RefreshCw size={18} />
                )}
              </button>
            </div>
            <div className="section-body">
              <div className="problem-content">
                <div className="content-bullets">
                  {currentStartup.problem.split('. ').slice(0, 5).map((point, index) => (
                    <div key={index} className="content-bullet problem-bullet" style={{animationDelay: `${index * 0.1}s`}}>
                      <div className="bullet-icon">
                        <Target size={16} />
                      </div>
                      <span className="bullet-text">{point.trim()}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        );
      case 'solution':
        return (
          <div className="section-content animate-fade-in">
            <div className="section-header">
              <div className="section-icon">
                <ZapIcon size={32} className="text-white" />
              </div>
              <div className="section-title-group">
                <h3 className="section-title">The Solution</h3>
                <p className="section-subtitle">How we address the problem</p>
              </div>
              <button
                onClick={() => handleRegenerateSection('solution')}
                disabled={regeneratingSection === 'solution'}
                className="section-regenerate-btn"
                title="Regenerate this section"
              >
                {regeneratingSection === 'solution' ? (
                  <Loader2 size={18} className="animate-spin" />
                ) : (
                  <RefreshCw size={18} />
                )}
              </button>
            </div>
            <div className="section-body">
              <div className="solution-content">
                <div className="content-bullets">
                  {currentStartup.solution.split('. ').slice(0, 5).map((point, index) => (
                    <div key={index} className="content-bullet solution-bullet" style={{animationDelay: `${index * 0.1}s`}}>
                      <div className="bullet-icon">
                        <ZapIcon size={16} />
                      </div>
                      <span className="bullet-text">{point.trim()}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        );
      case 'market':
        return (
          <div className="section-content animate-fade-in">
            <div className="section-header">
              <div className="section-icon">
                <UsersIcon size={32} className="text-white" />
              </div>
              <div className="section-title-group">
                <h3 className="section-title">Target Market</h3>
                <p className="section-subtitle">Who we're serving</p>
              </div>
              <button
                onClick={() => handleRegenerateSection('targetMarket')}
                disabled={regeneratingSection === 'targetMarket'}
                className="section-regenerate-btn"
                title="Regenerate this section"
              >
                {regeneratingSection === 'targetMarket' ? (
                  <Loader2 size={18} className="animate-spin" />
                ) : (
                  <RefreshCw size={18} />
                )}
              </button>
            </div>
            <div className="section-body">
              <div className="market-content">
                <div className="content-bullets">
                  {currentStartup.targetMarket.split('. ').slice(0, 5).map((point, index) => (
                    <div key={index} className="content-bullet market-bullet" style={{animationDelay: `${index * 0.1}s`}}>
                      <div className="bullet-icon">
                        <UsersIcon size={16} />
                      </div>
                      <span className="bullet-text">{point.trim()}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        );
      case 'business-model':
        return (
          <div className="section-content animate-fade-in">
            <div className="section-header">
              <div className="section-icon">
                <DollarSign size={32} className="text-white" />
              </div>
              <div className="section-title-group">
                <h3 className="section-title">Business Model</h3>
                <p className="section-subtitle">How we create and capture value</p>
              </div>
              <button
                onClick={() => handleRegenerateSection('businessModel')}
                disabled={regeneratingSection === 'businessModel'}
                className="section-regenerate-btn"
                title="Regenerate this section"
              >
                {regeneratingSection === 'businessModel' ? (
                  <Loader2 size={18} className="animate-spin" />
                ) : (
                  <RefreshCw size={18} />
                )}
              </button>
            </div>
            <div className="section-body">
              <div className="business-content">
                <div className="content-bullets">
                  {currentStartup.businessModel.split('. ').slice(0, 5).map((point, index) => (
                    <div key={index} className="content-bullet business-bullet" style={{animationDelay: `${index * 0.1}s`}}>
                      <div className="bullet-icon">
                        <DollarSign size={16} />
                      </div>
                      <span className="bullet-text">{point.trim()}</span>
                    </div>
                  ))}
                </div>
                <div className="tech-stack-section">
                  <div className="tech-stack-header">
                    <Globe size={24} className="text-primary" />
                    <h4 className="tech-stack-title">Tech Stack</h4>
                  </div>
                  <div className="tech-stack-tags">
                    {currentStartup.techStack.map((tech, index) => (
                      <span
                        key={index}
                        className="tech-tag animate-fade-in"
                        style={{animationDelay: `${index * 0.1}s`}}
                      >
                        {tech}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        );
      default:
        return null;
    }
  };

  return (
    <div className="startup-output-card fade-in">
      <div className="startup-card-header">
        <div className="header-content">
          <div className="header-left">
            <div className="header-icon">
              <Rocket size={28} className="text-white" />
            </div>
            <div className="header-text">
              <h2 className="header-title">Your Startup Idea</h2>
              <p className="header-subtitle">Complete business concept ready for execution</p>
            </div>
          </div>
          <div className="header-actions">
            {onRegenerate && (
              <button
                onClick={onRegenerate}
                className="action-btn hover-lift"
                title="Generate new idea"
              >
                <RefreshCw size={18} />
                <span>Remix</span>
              </button>
            )}
            <button 
              onClick={handleDownload}
              disabled={isDownloading}
              className="action-btn hover-lift"
              title="Download as PDF"
            >
              {isDownloading ? <div className="spinner w-4 h-4"></div> : <Download size={18} />}
            </button>
            <button 
              onClick={handleShare}
              disabled={isSharing}
              className="action-btn hover-lift"
              title="Share idea"
            >
              {isSharing ? <div className="spinner w-4 h-4"></div> : <Share2 size={18} />}
            </button>
          </div>
        </div>
      </div>

      {/* Modern Navigation Tabs */}
      <div className="modern-tabs">
        <div className="tabs-container">
          {sections.map((section) => {
            const Icon = section.icon;
            const isActive = activeSection === section.id;
            return (
              <button
                key={section.id}
                onClick={() => setActiveSection(section.id as 'overview' | 'problem' | 'solution' | 'market' | 'business-model')}
                className={`modern-tab ${isActive ? 'active' : ''} hover-lift`}
              >
                <div className="tab-icon">
                  <Icon size={20} />
                </div>
                <div className="tab-content">
                  <span className="tab-label">{section.label}</span>
                  <span className="tab-description">{section.description}</span>
                </div>
                {isActive && <div className="tab-indicator"></div>}
              </button>
            );
          })}
        </div>
      </div>

      {/* Content Area */}
      <div className="startup-card-body">
        <div className="content-container">
          {renderSection()}
        </div>
      </div>

      {/* Enhanced Action Buttons */}
      <div className="startup-card-footer">
        <div className="footer-actions">
          <button
            onClick={handleGenerateCanvas}
            disabled={isGeneratingCanvas}
            className="action-button primary hover-scale"
          >
            <FileText size={22} />
            <span>Generate Business Model Canvas</span>
            <ChevronRight size={18} />
          </button>
          <button
            onClick={handleGenerateMockup}
            disabled={isGeneratingMockup}
            className="action-button secondary hover-scale"
          >
            <Smartphone size={22} />
            <span>Generate App Mockup</span>
            <ChevronRight size={18} />
          </button>
        </div>
      </div>

      {/* Business Model Canvas Section */}
      {showCanvas && canvasData && (
        <div className="canvas-section animate-fade-in">
          <div className="section-header">
            <div className="section-icon">
              <Layout size={32} className="text-white" />
            </div>
            <div className="section-title-group">
              <h3 className="section-title">Business Model Canvas</h3>
              <p className="section-subtitle">Strategic framework for {currentStartup.name}</p>
            </div>
            <button
              onClick={() => setShowCanvas(false)}
              className="section-close-btn"
              title="Close canvas"
            >
              <X size={18} />
            </button>
          </div>
          
          <div className="canvas-grid">
            <div className="canvas-cell partners">
              <h4 className="canvas-cell-title">Key Partners</h4>
              <div className="canvas-cell-content">
                {canvasData.keyPartners.map((partner: string, index: number) => (
                  <div key={index} className="canvas-item">
                    <div className="canvas-item-icon">
                      <UsersIcon size={16} />
                    </div>
                    <span>{partner}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="canvas-cell activities">
              <h4 className="canvas-cell-title">Key Activities</h4>
              <div className="canvas-cell-content">
                {canvasData.keyActivities.map((activity: string, index: number) => (
                  <div key={index} className="canvas-item">
                    <div className="canvas-item-icon">
                      <Settings size={16} />
                    </div>
                    <span>{activity}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="canvas-cell value">
              <h4 className="canvas-cell-title">Value Propositions</h4>
              <div className="canvas-cell-content">
                <div className="canvas-item highlight">
                  <div className="canvas-item-icon">
                    <Star size={16} />
                  </div>
                  <span>{canvasData.valuePropositions}</span>
                </div>
              </div>
            </div>
            
            <div className="canvas-cell relationships">
              <h4 className="canvas-cell-title">Customer Relationships</h4>
              <div className="canvas-cell-content">
                {canvasData.customerRelationships.map((relationship: string, index: number) => (
                  <div key={index} className="canvas-item">
                    <div className="canvas-item-icon">
                      <Heart size={16} />
                    </div>
                    <span>{relationship}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="canvas-cell segments">
              <h4 className="canvas-cell-title">Customer Segments</h4>
              <div className="canvas-cell-content">
                <div className="canvas-item highlight">
                  <div className="canvas-item-icon">
                    <TargetIcon size={16} />
                  </div>
                  <span>{canvasData.customerSegments}</span>
                </div>
              </div>
            </div>
            
            <div className="canvas-cell resources">
              <h4 className="canvas-cell-title">Key Resources</h4>
              <div className="canvas-cell-content">
                {canvasData.keyResources.map((resource: string, index: number) => (
                  <div key={index} className="canvas-item">
                    <div className="canvas-item-icon">
                      <Database size={16} />
                    </div>
                    <span>{resource}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="canvas-cell channels">
              <h4 className="canvas-cell-title">Channels</h4>
              <div className="canvas-cell-content">
                {canvasData.channels.map((channel: string, index: number) => (
                  <div key={index} className="canvas-item">
                    <div className="canvas-item-icon">
                      <Globe size={16} />
                    </div>
                    <span>{channel}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="canvas-cell costs">
              <h4 className="canvas-cell-title">Cost Structure</h4>
              <div className="canvas-cell-content">
                {canvasData.costStructure.map((cost: string, index: number) => (
                  <div key={index} className="canvas-item">
                    <div className="canvas-item-icon">
                      <DollarIcon size={16} />
                    </div>
                    <span>{cost}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="canvas-cell revenue">
              <h4 className="canvas-cell-title">Revenue Streams</h4>
              <div className="canvas-cell-content">
                <div className="canvas-item highlight">
                  <div className="canvas-item-icon">
                    <TrendingUp size={16} />
                  </div>
                  <span>{canvasData.revenueStreams}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* App Mockup Section */}
      {showMockup && mockupData && (
        <div className="mockup-section animate-fade-in">
          <div className="section-header">
            <div className="section-icon">
              <Smartphone size={32} className="text-white" />
            </div>
            <div className="section-title-group">
              <h3 className="section-title">App Mockup</h3>
              <p className="section-subtitle">UI/UX specifications for {currentStartup.name}</p>
            </div>
            <button
              onClick={() => setShowMockup(false)}
              className="section-close-btn"
              title="Close mockup"
            >
              <X size={18} />
            </button>
          </div>
          
          <div className="mockup-content">
            <div className="mockup-screens">
              {mockupData.screens.map((screen: any, index: number) => (
                <div key={index} className="mockup-screen">
                  <div className="screen-header">
                    <h4 className="screen-title">{screen.name}</h4>
                    <div className="screen-number">{index + 1}</div>
                  </div>
                  <div className="screen-elements">
                    {screen.elements.map((element: any, elementIndex: number) => (
                      <div key={elementIndex} className="screen-element">
                        <div className="element-icon">
                          {element.type === 'logo' && <Image size={16} />}
                          {element.type === 'tagline' && <Type size={16} />}
                          {element.type === 'cta' && <MousePointer size={16} />}
                          {element.type === 'background' && <Palette size={16} />}
                          {element.type === 'profile' && <User size={16} />}
                          {element.type === 'menu' && <Menu size={16} />}
                                                     {element.type === 'progress' && <BarChartIcon size={16} />}
                          {element.type === 'feed' && <Activity size={16} />}
                          {element.type === 'interface' && <Layout size={16} />}
                          {element.type === 'navigation' && <Navigation size={16} />}
                          {element.type === 'buttons' && <Square size={16} />}
                          {element.type === 'status' && <Circle size={16} />}
                          {element.type === 'preferences' && <Settings size={16} />}
                          {element.type === 'account' && <Shield size={16} />}
                          {element.type === 'help' && <HelpCircle size={16} />}
                          {element.type === 'about' && <Info size={16} />}
                        </div>
                        <span className="element-content">{element.content}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
            
            <div className="design-system">
              <h4 className="design-system-title">Design System</h4>
              <div className="design-system-grid">
                <div className="design-item">
                  <h5>Primary Colors</h5>
                  <div className="color-palette">
                    {mockupData.designSystem.primaryColors.map((color: string, index: number) => (
                      <div key={index} className="color-swatch">
                        <div className="color-preview"></div>
                        <span>{color}</span>
                      </div>
                    ))}
                  </div>
                </div>
                <div className="design-item">
                  <h5>Typography</h5>
                  <p>{mockupData.designSystem.typography}</p>
                </div>
                <div className="design-item">
                  <h5>Icons</h5>
                  <p>{mockupData.designSystem.icons}</p>
                </div>
                <div className="design-item">
                  <h5>Spacing</h5>
                  <p>{mockupData.designSystem.spacing}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default StartupOutput; 